In [2]:
import numpy as np

In [3]:
# demonstrating assignment in numpy

In [4]:
a = np.arange(5)
b = np.arange(10)
print(b)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [5]:
a[0] = 12
a

array([12,  1,  2,  3,  4])

In [6]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [7]:
a[3:]

array([3, 4])

In [8]:
# you can assign a value to a slice of an array
# this assigns that same value to every element in the slice
a[3:] = -1
a

array([ 0,  1,  2, -1, -1])

In [10]:
# my_array is not defined yet
my_array[14] = -102

NameError: name 'my_array' is not defined

In [ ]:
# but it gets defined here!
# if you run this cell and THEN run the cell above, it'll work.
# that's weird.
# make sure you try running all your cells in order
# so that you can be certain there are no loopy weird things
# (by doing Kernel>Restart and then Cell>Run All)
my_array = np.arange(20)
my_array

In [11]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# you can even assign a value to weird slice of an array like this one
a[::3] = -1
a

array([-1,  1,  2, -1,  4,  5, -1,  7,  8, -1])

In [13]:
# you can also assign values to multidimensional slices
arr = np.zeros((10,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
# here the slice [:5,:5] (which is 25 elements: the first
# 5 rows of the first 5 columns) all gets assigned the value 1
arr[:5,:5] = 1
arr

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
# instead of assigning single values you can also assign a list or array of values
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [17]:
a[:2] = [99, 98]
a

array([99, 98,  2,  3,  4])

In [18]:
# this is useful if you want to modify part of an array:
# first slice it, then assign the modified value back to that slice!
arr[:,3:6] = arr[:,3:6] - 10
arr

array([[  1.,   1.,   1.,  -9.,  -9., -10.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,  -9.,  -9., -10.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,  -9.,  -9., -10.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,  -9.,  -9., -10.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,  -9.,  -9., -10.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., -10., -10., -10.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., -10., -10., -10.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., -10., -10., -10.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., -10., -10., -10.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., -10., -10., -10.,   0.,   0.,   0.,   0.]])

In [19]:
# you can also accomplish this using the "in-place" operators, like +=, *=, -=, etc.
arr[:2] += 10
# same as: arr[:2] = arr[:2] + 10
arr

array([[ 11.,  11.,  11.,   1.,   1.,   0.,  10.,  10.,  10.,  10.],
       [ 11.,  11.,  11.,   1.,   1.,   0.,  10.,  10.,  10.,  10.],
       [  1.,   1.,   1.,  -9.,  -9., -10.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,  -9.,  -9., -10.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,  -9.,  -9., -10.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., -10., -10., -10.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., -10., -10., -10.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., -10., -10., -10.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., -10., -10., -10.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., -10., -10., -10.,   0.,   0.,   0.,   0.]])

In [20]:
# views

In [21]:
# lil_a is a _view_ on the last 5 elements of a
a = np.arange(10)
lil_a = a[5:]
lil_a

array([5, 6, 7, 8, 9])

In [22]:
# so if we modify lil_a..
lil_a[0] = 17
lil_a

array([17,  6,  7,  8,  9])

In [23]:
# ..it also modifies a!
a

array([ 0,  1,  2,  3,  4, 17,  6,  7,  8,  9])

In [24]:
# and, if we modify a..
a[-1] = 0
a

array([ 0,  1,  2,  3,  4, 17,  6,  7,  8,  0])

In [25]:
# it also modifies lil_a!
# this happens because both lil_a and a are views on the exact same memory
lil_a

array([17,  6,  7,  8,  0])

In [26]:
# the same is true if we do a weirder slice like this one
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# every_other_b is still a view on the same memory as b
every_other_b = b[::2]
every_other_b

array([0, 2, 4, 6, 8])

In [28]:
every_other_b[2] = -4
every_other_b

array([ 0,  2, -4,  6,  8])

In [29]:
b

array([ 0,  1,  2,  3, -4,  5,  6,  7,  8,  9])

In [30]:
# this can have unintended consequences! running this function multiplies element 14
# of the input arr by -1, and then returns the result
def my_silly_function(arr):
    arr[14] *= -1
    return arr

my_array = np.arange(20)
my_new_array = my_silly_function(my_array)
my_new_array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13, -14,  15,  16,  17,  18,  19])

In [31]:
# but the original arr is modified as well!
my_array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13, -14,  15,  16,  17,  18,  19])

In [32]:
# calling the function more than once will undo its effect!
# this is super super weird. you should avoid this.
my_silly_function(my_array)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
my_new_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
# to get around the problem of different variables being views on the same data,
# you can use the .copy() method, which creates a new copy of the array in memory

def my_silly_function_2(arr):
    my_arr = arr.copy()
    my_arr[14] *= -1
    return my_arr

my_array = np.arange(20)
my_new_array = my_silly_function_2(my_array)
my_new_array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13, -14,  15,  16,  17,  18,  19])

In [37]:
# you can safely edit the copy without affecting the original
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
# this exact situation also holds true for lists!
# (but not always: slices of lists are not views)
# to force a list to copy, wrap it in list()

def my_list_function(li):
    #my_li = list(li) # copies the list
    my_li = li # edits the original list
    my_li[14] *= -1
    return my_li

my_list = list(range(20))
my_new_list = my_list_function(my_list)
my_new_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, -14, 15, 16, 17, 18, 19]

In [41]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, -14, 15, 16, 17, 18, 19]

In [42]:
# indexing instead of slicing DOES NOT create a view, but instead automatically
# creates a copy of the data
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
inds = [0, 4, 5, -1]
ind_a = a[inds]
ind_a

array([0, 4, 5, 9])

In [45]:
# so modifying ind_a..
ind_a[0] = 12
ind_a

array([12,  4,  5,  9])

In [46]:
# ..doesn't affect a!
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# while modifying the sliced version, sl_a, will
sl_a = a[:5]
sl_a

array([0, 1, 2, 3, 4])

In [48]:
# you can tell whether any array actually "owns" its data, or whether it is a 
# view on another array's data by looking at the .flags attribute
# here a.flags has OWNDATA : True, meaning that it owns this data (it is not a view)
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [49]:
# similarly, ind_a has OWNDATA : True because it also owns its data 
# (since it was created by indexing a, which forced a copy!)
ind_a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [50]:
# but the slice sl_a created a VIEW, not a COPY, so it does not own its data,
# and it has OWNDATA : False!
sl_a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False