In [1]:
import numpy as np

In [2]:
a = np.ones(10)
b = np.arange(10)
print(a)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
(a + b).shape

(10,)

In [5]:
(a + b)[0] == a[0] + b[0]

True

In [6]:
a + b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
np.set_printoptions(precision=2)

In [9]:
arr = np.random.rand(50,10)
to_add = np.arange(10)
print(arr)

[[0.16 0.64 0.47 0.72 0.81 0.05 0.74 0.2  0.84 0.  ]
 [0.61 0.5  0.15 0.59 0.11 0.45 0.45 0.24 0.27 0.26]
 [0.03 0.05 0.76 0.89 0.38 0.33 0.67 0.63 0.14 0.06]
 [0.02 0.15 0.04 0.7  0.89 0.52 0.52 0.48 0.41 0.69]
 [0.62 0.58 0.01 0.39 0.24 0.73 0.87 0.66 0.84 0.12]
 [0.2  0.6  0.84 0.74 0.99 0.78 0.51 0.33 0.93 0.34]
 [0.27 0.25 0.94 0.08 0.22 0.28 0.19 0.38 0.02 0.5 ]
 [0.13 0.92 0.93 0.78 0.44 0.88 0.7  0.29 0.19 0.54]
 [0.8  0.67 0.64 0.01 0.79 0.77 0.02 0.31 0.78 0.03]
 [0.26 0.38 0.91 0.93 0.88 0.15 0.89 0.32 0.51 0.42]
 [0.59 0.72 0.43 0.34 0.56 0.4  0.46 0.99 0.42 0.12]
 [0.19 0.39 0.71 0.78 0.05 0.46 0.78 0.27 0.48 0.49]
 [0.14 0.36 0.85 0.72 0.24 0.29 0.97 0.01 0.86 0.26]
 [0.26 0.63 0.77 0.64 0.67 0.59 0.85 0.78 0.12 0.93]
 [0.33 0.23 0.83 0.08 0.87 0.1  0.21 0.57 0.41 0.96]
 [0.83 0.49 0.18 0.91 0.82 0.78 0.82 0.41 0.8  0.15]
 [0.53 0.36 0.86 0.25 0.58 0.91 0.76 0.13 0.16 0.94]
 [0.57 0.41 0.55 0.62 0.24 0.91 0.08 0.44 0.36 0.55]
 [0.24 0.86 0.95 0.06 0.27 0.85 0.88 0.51 0.5 

In [10]:
print(to_add)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
arr[0]

array([0.16, 0.64, 0.47, 0.72, 0.81, 0.05, 0.74, 0.2 , 0.84, 0.  ])

In [14]:
# first row should be
arr[0] + to_add

array([0.16, 1.64, 2.47, 3.72, 4.81, 5.05, 6.74, 7.2 , 8.84, 9.  ])

In [15]:
# we could write a for loop
result = np.zeros((50,10))
for ii in range(50):
    result[ii] = arr[ii] + to_add

# this suuuucks

In [16]:
print(result)

[[0.16 1.64 2.47 3.72 4.81 5.05 6.74 7.2  8.84 9.  ]
 [0.61 1.5  2.15 3.59 4.11 5.45 6.45 7.24 8.27 9.26]
 [0.03 1.05 2.76 3.89 4.38 5.33 6.67 7.63 8.14 9.06]
 [0.02 1.15 2.04 3.7  4.89 5.52 6.52 7.48 8.41 9.69]
 [0.62 1.58 2.01 3.39 4.24 5.73 6.87 7.66 8.84 9.12]
 [0.2  1.6  2.84 3.74 4.99 5.78 6.51 7.33 8.93 9.34]
 [0.27 1.25 2.94 3.08 4.22 5.28 6.19 7.38 8.02 9.5 ]
 [0.13 1.92 2.93 3.78 4.44 5.88 6.7  7.29 8.19 9.54]
 [0.8  1.67 2.64 3.01 4.79 5.77 6.02 7.31 8.78 9.03]
 [0.26 1.38 2.91 3.93 4.88 5.15 6.89 7.32 8.51 9.42]
 [0.59 1.72 2.43 3.34 4.56 5.4  6.46 7.99 8.42 9.12]
 [0.19 1.39 2.71 3.78 4.05 5.46 6.78 7.27 8.48 9.49]
 [0.14 1.36 2.85 3.72 4.24 5.29 6.97 7.01 8.86 9.26]
 [0.26 1.63 2.77 3.64 4.67 5.59 6.85 7.78 8.12 9.93]
 [0.33 1.23 2.83 3.08 4.87 5.1  6.21 7.57 8.41 9.96]
 [0.83 1.49 2.18 3.91 4.82 5.78 6.82 7.41 8.8  9.15]
 [0.53 1.36 2.86 3.25 4.58 5.91 6.76 7.13 8.16 9.94]
 [0.57 1.41 2.55 3.62 4.24 5.91 6.08 7.44 8.36 9.55]
 [0.24 1.86 2.95 3.06 4.27 5.85 6.88 7.51 8.5 

In [17]:
# with broadcasting
arr + to_add

array([[0.16, 1.64, 2.47, 3.72, 4.81, 5.05, 6.74, 7.2 , 8.84, 9.  ],
       [0.61, 1.5 , 2.15, 3.59, 4.11, 5.45, 6.45, 7.24, 8.27, 9.26],
       [0.03, 1.05, 2.76, 3.89, 4.38, 5.33, 6.67, 7.63, 8.14, 9.06],
       [0.02, 1.15, 2.04, 3.7 , 4.89, 5.52, 6.52, 7.48, 8.41, 9.69],
       [0.62, 1.58, 2.01, 3.39, 4.24, 5.73, 6.87, 7.66, 8.84, 9.12],
       [0.2 , 1.6 , 2.84, 3.74, 4.99, 5.78, 6.51, 7.33, 8.93, 9.34],
       [0.27, 1.25, 2.94, 3.08, 4.22, 5.28, 6.19, 7.38, 8.02, 9.5 ],
       [0.13, 1.92, 2.93, 3.78, 4.44, 5.88, 6.7 , 7.29, 8.19, 9.54],
       [0.8 , 1.67, 2.64, 3.01, 4.79, 5.77, 6.02, 7.31, 8.78, 9.03],
       [0.26, 1.38, 2.91, 3.93, 4.88, 5.15, 6.89, 7.32, 8.51, 9.42],
       [0.59, 1.72, 2.43, 3.34, 4.56, 5.4 , 6.46, 7.99, 8.42, 9.12],
       [0.19, 1.39, 2.71, 3.78, 4.05, 5.46, 6.78, 7.27, 8.48, 9.49],
       [0.14, 1.36, 2.85, 3.72, 4.24, 5.29, 6.97, 7.01, 8.86, 9.26],
       [0.26, 1.63, 2.77, 3.64, 4.67, 5.59, 6.85, 7.78, 8.12, 9.93],
       [0.33, 1.23, 2.83, 3.08, 4.

In [18]:
a = np.ones((2,3,4))
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [20]:
b = np.arange(4)
print(b)
print(b.shape)

[0 1 2 3]
(4,)


In [22]:
padded_b = b.reshape((1,1,4))
print(padded_b.shape)
print(a.shape)

(1, 1, 4)
(2, 3, 4)


In [23]:
a + b

array([[[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]],

       [[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]]])

In [25]:
c = np.arange(3)
print(c)

[0 1 2]


In [29]:
padded_c = c.reshape((1,3,1))
print(padded_c.shape)
print(a.shape)

(1, 3, 1)
(2, 3, 4)


In [28]:
a + padded_c

array([[[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]],

       [[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]]])

In [30]:
a + c

ValueError: operands could not be broadcast together with shapes (2,3,4) (3,) 

In [32]:
d = np.arange(2)
print(d)
print(d.shape)

[0 1]
(2,)


In [33]:
a + d

ValueError: operands could not be broadcast together with shapes (2,3,4) (2,) 

In [34]:
a + d.reshape((2,1,1))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [35]:
a + d[:,np.newaxis,np.newaxis]

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [36]:
d[:,np.newaxis,np.newaxis].shape

(2, 1, 1)